site_name: Super web Scripts

nav:
    - Home: index.md
    - Glossary: glossary.md
    - Contribution Guide: contribution-guide.md

theme: readthedocs

repo_url: https://github.com/Descent098/sws

site_description: Super Web scripts documentation

site_author: Kieran Wood | Descent098